apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-test
  labels:
    app: l_mongodb-test
spec:
  replicas: 1
  serviceName: 'mongodb-test'
  selector:
    matchLabels:
      app: l_mongodb-test
  template:
    metadata:
      labels:
        app: l_mongodb-test
    spec:
      volumes:
        - name: apiatori-mongo-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc-testing
      containers:
        - name: mongodb
          image: mongo:latest
          volumeMounts:
            - mountPath: '/data/db'
              name: apiatori-mongo-storage
          env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: "apiatori"
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: "apiatori"
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  type: ClusterIP
  selector:
    app: l_mongodb-test
  ports:
    - name: mongodb-test
      protocol: TCP
      port: 27018
      targetPort: 27017