name: CI/CD develop

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  integration:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v2
  - name: Use Node.js 13.x
    uses: actions/setup-node@v2
    with:
      node-version: 13.x
  - run: npm install
  - run: npm install --save jest
  - run: npm test