name: CI/CD production

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 13.x
      uses: actions/setup-node@v2
      with:
        node-version: 13.x
    - run: npm install
    - run: npm install --save jest
    - run: npm test
  deployment:
    needs: integration
    runs-on: ubuntu-latest
    steps:
    - name: update terraform deployment in master
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          su - eval
          cd ./APIatori
          git pull origin master
          cd ./deployment/production
          terraform init
          terraform destroy -auto-approve
          terraform apply -auto-approve
